version: 1
from: "infracamp/kickstart-flavor-gaia:testing"

command:
  build:
    - "sudo scripts/install.sh"
    - "composer update"
  run:
  dev:


  update:
    - "sudo vendor/bin/cloudtool --tpldir /opt/etc --target /etc"

  interval:

