version: 1
from: "infracamp/kickstart-flavor-base:testing"

command:
  build:
    - "sudo scripts/install.sh"
  run:
  dev:

  update:
    - "sudo vendor/bin/cloudtool --tpldir /opt/etc --target /etc"

  interval: